//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abc.Processor {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Abc.Tools.StronglyTypedResourceBuilderEx", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public sealed class SR {
        
        private static global::System.Resources.ResourceManager resourceManager;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        private SR() {
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceManager, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Abc.Processor.SR", typeof(SR).Assembly);
                    resourceManager = temp;
                }
                return resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Failed to abort processor. {0}'.
        /// </summary>
        public static string AbortFailed {
            get {
                return ResourceManager.GetString("AbortFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Processor aborted successfully.'.
        /// </summary>
        public static string AbortSuccessful {
            get {
                return ResourceManager.GetString("AbortSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The specified attribute &apos;{0}&apos; is not supported by type &apos;{1}&apos;.'.
        /// </summary>
        public static string AttributeNotSupported {
            get {
                return ResourceManager.GetString("AttributeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'There was an error loading the {0} configuration section.'.
        /// </summary>
        public static string ConfigurationSectionError {
            get {
                return ResourceManager.GetString("ConfigurationSectionError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Could not create &apos;{0}&apos;.'.
        /// </summary>
        public static string CouldNotCreateTypeInstance {
            get {
                return ResourceManager.GetString("CouldNotCreateTypeInstance", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Couldn&apos;t find type for class &apos;{0}&apos;.'.
        /// </summary>
        public static string CouldNotFindType {
            get {
                return ResourceManager.GetString("CouldNotFindType", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Couldn&apos;t find constructor for class &apos;{0}&apos;.'.
        /// </summary>
        public static string CouldNotGetConstructor {
            get {
                return ResourceManager.GetString("CouldNotGetConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'switchType needs to be a valid class name. It can&apos;t be empty.'.
        /// </summary>
        public static string EmptyTypeNameNotAllowed {
            get {
                return ResourceManager.GetString("EmptyTypeNameNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'weekdays can&apos;t be empty'.
        /// </summary>
        public static string EmptyWeekdays {
            get {
                return ResourceManager.GetString("EmptyWeekdays", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Attribute value can not convert to type &apos;{0}&apos; for class &apos;{1}&apos;'.
        /// </summary>
        public static string ErrorConvertingAttribute {
            get {
                return ResourceManager.GetString("ErrorConvertingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The specified type, &apos;{0}&apos; is not derived from the appropriate base type, &apos;{1}&apos;.'.
        /// </summary>
        public static string IncorrectBaseType {
            get {
                return ResourceManager.GetString("IncorrectBaseType", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'InvalidOperation_EmptyQueue'.
        /// </summary>
        public static string InvalidOperationEmptyQueue {
            get {
                return ResourceManager.GetString("InvalidOperationEmptyQueue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error converting to weekday'.
        /// </summary>
        public static string InvalidWeekdayFormat {
            get {
                return ResourceManager.GetString("InvalidWeekdayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'NotSupportedMemberType'.
        /// </summary>
        public static string NotSupportedMemberType {
            get {
                return ResourceManager.GetString("NotSupportedMemberType", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Trigger &apos;{0}&apos; does not exist in the sharedTriggers section.'.
        /// </summary>
        public static string ReferenceToNonexistentTrigger {
            get {
                return ResourceManager.GetString("ReferenceToNonexistentTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Processor cannot be started. {0}'.
        /// </summary>
        public static string StartFailed {
            get {
                return ResourceManager.GetString("StartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Starting processor {0}...'.
        /// </summary>
        public static string StartingProcessor {
            get {
                return ResourceManager.GetString("StartingProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Processor started successfully.'.
        /// </summary>
        public static string StartSuccessful {
            get {
                return ResourceManager.GetString("StartSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Failed to stop processor. {0}'.
        /// </summary>
        public static string StopFailed {
            get {
                return ResourceManager.GetString("StopFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Processor stopped successfully.'.
        /// </summary>
        public static string StopSuccessful {
            get {
                return ResourceManager.GetString("StopSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Failed to abort processor. {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string AbortFailedFormat(object arg0) {
            return string.Format(resourceCulture, AbortFailed, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'The specified attribute &apos;{0}&apos; is not supported by type &apos;{1}&apos;.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string AttributeNotSupportedFormat(object arg0, object arg1) {
            return string.Format(resourceCulture, AttributeNotSupported, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'There was an error loading the {0} configuration section.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string ConfigurationSectionErrorFormat(object arg0) {
            return string.Format(resourceCulture, ConfigurationSectionError, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Could not create &apos;{0}&apos;.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string CouldNotCreateTypeInstanceFormat(object arg0) {
            return string.Format(resourceCulture, CouldNotCreateTypeInstance, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Couldn&apos;t find type for class &apos;{0}&apos;.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string CouldNotFindTypeFormat(object arg0) {
            return string.Format(resourceCulture, CouldNotFindType, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Couldn&apos;t find constructor for class &apos;{0}&apos;.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string CouldNotGetConstructorFormat(object arg0) {
            return string.Format(resourceCulture, CouldNotGetConstructor, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Attribute value can not convert to type &apos;{0}&apos; for class &apos;{1}&apos;'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string ErrorConvertingAttributeFormat(object arg0, object arg1) {
            return string.Format(resourceCulture, ErrorConvertingAttribute, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'The specified type, &apos;{0}&apos; is not derived from the appropriate base type, &apos;{1}&apos;.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string IncorrectBaseTypeFormat(object arg0, object arg1) {
            return string.Format(resourceCulture, IncorrectBaseType, arg0, arg1);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Trigger &apos;{0}&apos; does not exist in the sharedTriggers section.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string ReferenceToNonexistentTriggerFormat(object arg0) {
            return string.Format(resourceCulture, ReferenceToNonexistentTrigger, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Processor cannot be started. {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string StartFailedFormat(object arg0) {
            return string.Format(resourceCulture, StartFailed, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Starting processor {0}...'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string StartingProcessorFormat(object arg0) {
            return string.Format(resourceCulture, StartingProcessor, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Failed to stop processor. {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string StopFailedFormat(object arg0) {
            return string.Format(resourceCulture, StopFailed, arg0);
        }
    }
}
